### PR TITLE
Use getpass for pw-like input

### PR DESCRIPTION
**Pull request by haakonvt**
Love the work here! I changed the input to getpass for sensitive info. Also cleaned up some of the logic, feel free to accept only parts of the pr :)

### CODE REVIEW

**Comment by tducret** [comment]
Thank you very much @haakonvt 
I merged most of your modifications.
I didn't keep getpass since it was used to hide a temporary SMS token (which is not critical at all).
_Details in PR #6_
`revolut`package is now updated to **v0.0.7**

**Comment by haakonvt** [comment]
Alright! 👍🏼 What about `What is your Revolut app password [ex: 1234] ? ")`? Shouldn’t that be kept somewhat more secret?

**Comment by tducret** [comment]
You are right. I missed it.
I'll update it (and fix a bug I introduced) in the following days.

**Comment by tducret** [comment]
Hi @haakonvt. I released `v0.0.8` to use `getpass` for the password input (+ fix a wrong argument)

**Pull request closed without merging**
