### PR TITLE
add --account option

### PR DESCRIPTION
**Pull request by sentriz**
hello, 
thank you for making this.

I'm using it in my i3 bar [(see blocklet)](https://github.com/sentriz/dotfiles/blob/3ecb8ea680c41fd65e50cd94a73043ba29c5a7fc/public_extra/.config/i3blocks/blocklets/balance#L14-L19)

as you can see, from the script, I'm getting the second line of the output of revolut_cli.py (the 0th account) using sed and awk 

this PR would mean I wouldn't have to use sed / awk

### CODE REVIEW

**Comment by tducret** [comment]
Hi @sentriz !
Very nice i3 blocklet 👍 
What would you think to add the --account option but with <Wallet_currency> as a parameter ?
For instance `revolut_cli.py --account EUR`

**Comment by sentriz** [comment]
hey
thank you :)

I'm not sure how that would work (I'm new to revolut) because I seem to have two EUR accounts (I _think_ the second one is one of my vaults)

```
revolut_cli.py --token (pass money/revolut/token)
Nom du compte;Solde;Devise
EUR wallet;23,98;EUR
EUR wallet;0,00;EUR
```
I'll check now

**Comment by tducret** [comment]
In this case, I can add this information like this :

revolut_cli.py --token (pass money/revolut/token)
Nom du compte;Solde;Devise
EUR CURRENT;23,98;EUR
EUR VAULT;0,00;EUR

I have to check that I can get the "VAULT" attribute.

Le jeu. 19 juil. 2018 à 22:16, Senan Kelly <notifications@github.com> a
écrit :

**Comment by sentriz** [comment]
ok, i've done something similar to what you've said 
```
$ revolut_cli.py
Nom du compte;Solde;Devise
EUR wallet;22,98;EUR
EUR wallet (tech);1,00;EUR
$ revolut_cli.py --account EUR
22.98
$ revolut_cli.py --account "EUR tech"
1.00
```

note: 
  - i have two EUR wallets
  - one of them is a vault with the name "tech"
  - if you search for just "EUR" and you have multiple wallets with the same currency, it picks the first one
  - you can pass a second word to `--account` and it will try to find the name

**Comment by tducret** [comment]
Thank you for your help. I didn't implement it in this way (no offense :)

I didn't add the flexibility on the account name, and you get the account balance without csv with the --account option.
```bash
revolut_cli.py --account "EUR CURRENT"
25.35 EUR
```
or

```bash
revolut_cli.py --account "EUR SAVINGS (My vault)"
155.45 EUR
```

Feel free to upgrade the revolut Pypi package (v0.0.6) to test it

**Comment by sentriz** [comment]
great thank you :) 
[updated blocklet](https://github.com/sentriz/dotfiles/commit/2bac7d73fdf0ca691bc45192feeb2173b362f663)

**Pull request closed without merging**
